commented the exit code

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -56,6 +56,6 @@ jobs:
               run: terraform plan -out=tfplan
               continue-on-error: true
 
-            - name: Terraform plan output
-              if: steps.terraform_plan.outcome == 'failure'
-              run: exit 1
+            # - name: Terraform plan output
+            #   if: steps.terraform_plan.outcome == 'failure'
+            #   run: exit 1
